services:
  db:
    image: postgres:17
    container_name: ironcore_postgres
    environment:
      POSTGRES_USER: ${DB_USER_DEV}
      POSTGRES_PASSWORD: ${DB_PASSWORD_DEV}
      POSTGRES_DB: ironcore_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: ironcore_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER_DEV}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD_DEV}
      MONGO_INITDB_DATABASE: ironcore_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.5.0
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#
#  kafka:
#    image: confluentinc/cp-kafka:7.5.0
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  pgdata:
  mongodata:
