spring:
  application:
    name: ironcore-backend
  config:
    import: optional:file:.env[.properties]

  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{correlationId}] %logger{36} - %msg%n"

security:
  token:
    secret: ${JWT_SECRET}

app:
  name: IronCore
  version: 0.1.0
  environment: default

ironcore:
  bootstrap:
    person:
      enabled: ${IRONCORE_BOOTSTRAP_PERSON_ENABLED:false}
      name: ${IRONCORE_BOOTSTRAP_PERSON_NAME:}
      sex: ${IRONCORE_BOOTSTRAP_PERSON_SEX:}
      birth-date: ${IRONCORE_BOOTSTRAP_PERSON_BIRTH_DATE:}

    single-user:
      enabled: ${IRONCORE_BOOTSTRAP_USER_ENABLED:false}
      nickname: ${IRONCORE_BOOTSTRAP_USER_NICKNAME:}
      person-name: ${IRONCORE_BOOTSTRAP_PERSON_NAME:}
      email: ${IRONCORE_BOOTSTRAP_USER_EMAIL:}
      password: ${IRONCORE_BOOTSTRAP_USER_PASSWORD:}
