-- 341 exercícios.
-- Pré-requisitos: seeds de activity_types e equipment_types.
-- As associações com muscle_groups e muscle_subgroups pertencem à migration
-- de exercise_muscle_targets e não fazem parte desta tabela.
--
-- Variações específicas com anilha não foram inseridas porque WEIGHT_PLATE
-- não existe no seed aprovado de equipment_types:
--   - Elevação frontal
--   - Prancha com peso
--   - Crunch abdominal com carga

WITH exercise_seed (
                    name,
                    equipment_code,
                    activity_code,
                    unilateral,
                    compound,
                    suggested_rest_seconds
    ) AS (
    VALUES
        -- Peitoral
        ('Supino reto', 'BARBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Supino reto', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Supino reto', 'MACHINE', 'STRENGTH', FALSE, TRUE, 120),
        ('Supino inclinado', 'BARBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Supino inclinado', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Supino inclinado', 'MACHINE', 'STRENGTH', FALSE, TRUE, 120),
        ('Supino declinado', 'BARBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Supino declinado', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Supino declinado', 'MACHINE', 'STRENGTH', FALSE, TRUE, 120),
        ('Crucifixo reto', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Crucifixo reto', 'MACHINE', 'STRENGTH', FALSE, FALSE, 75),
        ('Crucifixo inclinado', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Crucifixo declinado', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Crossover alto', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Crossover médio', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Crossover baixo', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Pullover', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 90),
        ('Pullover', 'BARBELL', 'STRENGTH', FALSE, FALSE, 90),
        ('Pullover', 'MACHINE', 'STRENGTH', FALSE, FALSE, 90),
        ('Flexão de braços', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 90),
        ('Flexão inclinada', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 75),
        ('Flexão declinada', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 90),
        ('Flexão diamante', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 90),
        ('Flexão arqueiro', 'BODYWEIGHT', 'STRENGTH', TRUE, TRUE, 90),
        ('Mergulho nas paralelas', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 120),
        -- Costas e trapézio
        ('Barra fixa pronada', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 150),
        ('Barra fixa supinada', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 150),
        ('Barra fixa com pegada neutra', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 150),
        ('Puxada frontal com pegada aberta', 'CABLE', 'STRENGTH', FALSE, TRUE, 120),
        ('Puxada frontal com pegada supinada', 'CABLE', 'STRENGTH', FALSE, TRUE, 120),
        ('Puxada frontal com pegada neutra fechada', 'CABLE', 'STRENGTH', FALSE, TRUE, 120),
        ('Puxada frontal unilateral', 'CABLE', 'STRENGTH', TRUE, TRUE, 90),
        ('Pulldown com braços estendidos', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Remada curvada', 'BARBELL', 'STRENGTH', FALSE, TRUE, 150),
        ('Remada unilateral', 'DUMBBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Remada cavalinho', 'BARBELL', 'STRENGTH', FALSE, TRUE, 150),
        ('Remada cavalinho', 'MACHINE', 'STRENGTH', FALSE, TRUE, 120),
        ('Remada sentada com pegada neutra', 'CABLE', 'STRENGTH', FALSE, TRUE, 120),
        ('Remada sentada com pegada aberta', 'CABLE', 'STRENGTH', FALSE, TRUE, 120),
        ('Remada bilateral', 'MACHINE', 'STRENGTH', FALSE, TRUE, 120),
        ('Remada unilateral', 'MACHINE', 'STRENGTH', TRUE, TRUE, 120),
        ('Remada invertida', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 120),
        ('Levantamento terra', 'BARBELL', 'STRENGTH', FALSE, TRUE, 180),
        ('Levantamento terra', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 180),
        ('Levantamento terra', 'KETTLEBELL', 'STRENGTH', FALSE, TRUE, 180),
        ('Levantamento terra sumô', 'BARBELL', 'STRENGTH', FALSE, TRUE, 180),
        ('Rack pull', 'BARBELL', 'STRENGTH', FALSE, TRUE, 180),
        ('Bom dia', 'BARBELL', 'STRENGTH', FALSE, TRUE, 150),
        ('Extensão lombar', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 90),
        ('Extensão lombar', 'MACHINE', 'STRENGTH', FALSE, TRUE, 90),
        ('Encolhimento de ombros', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 90),
        ('Encolhimento de ombros', 'BARBELL', 'STRENGTH', FALSE, FALSE, 90),
        ('Encolhimento de ombros', 'MACHINE', 'STRENGTH', FALSE, FALSE, 90),
        ('Face pull', 'CABLE', 'STRENGTH', FALSE, TRUE, 75),
        ('Face pull', 'BAND', 'STRENGTH', FALSE, TRUE, 75),
        ('Pulldown unilateral com braço estendido', 'CABLE', 'STRENGTH', TRUE, FALSE, 75),
        -- Ombros
        ('Desenvolvimento militar', 'BARBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Desenvolvimento militar', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Desenvolvimento militar', 'MACHINE', 'STRENGTH', FALSE, TRUE, 120),
        ('Desenvolvimento militar', 'KETTLEBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Desenvolvimento Arnold', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Desenvolvimento unilateral', 'DUMBBELL', 'STRENGTH', TRUE, TRUE, 90),
        ('Desenvolvimento unilateral', 'KETTLEBELL', 'STRENGTH', TRUE, TRUE, 90),
        ('Desenvolvimento unilateral em landmine', 'BARBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Elevação lateral', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação lateral', 'CABLE', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação lateral', 'MACHINE', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação lateral', 'BAND', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação lateral inclinada', 'DUMBBELL', 'STRENGTH', TRUE, FALSE, 60),
        ('Elevação lateral unilateral', 'CABLE', 'STRENGTH', TRUE, FALSE, 60),
        ('Elevação frontal', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação frontal', 'BARBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação frontal', 'CABLE', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação frontal', 'BAND', 'STRENGTH', FALSE, FALSE, 60),
        ('Crucifixo invertido', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Crucifixo invertido', 'MACHINE', 'STRENGTH', FALSE, FALSE, 75),
        ('Crucifixo invertido', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Crucifixo invertido', 'BAND', 'STRENGTH', FALSE, FALSE, 75),
        ('Remada alta', 'BARBELL', 'STRENGTH', FALSE, TRUE, 90),
        ('Remada alta', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 90),
        ('Remada alta', 'CABLE', 'STRENGTH', FALSE, TRUE, 90),
        ('Rotação externa de ombro', 'CABLE', 'STRENGTH', TRUE, FALSE, 60),
        ('Rotação externa de ombro', 'BAND', 'STRENGTH', TRUE, FALSE, 60),
        ('Rotação interna de ombro', 'CABLE', 'STRENGTH', TRUE, FALSE, 60),
        ('Rotação interna de ombro', 'BAND', 'STRENGTH', TRUE, FALSE, 60),
        ('Rotação externa de ombro deitado', 'DUMBBELL', 'STRENGTH', TRUE, FALSE, 60),
        ('Elevação em Y', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação em Y', 'CABLE', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação em Y', 'BAND', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação no plano escapular', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Flexão pike', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 90),
        ('Flexão em parada de mãos', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 150),
        ('Protração escapular', 'DUMBBELL', 'STRENGTH', TRUE, FALSE, 60),
        ('Protração escapular', 'CABLE', 'STRENGTH', TRUE, FALSE, 60),
        ('Protração escapular', 'BAND', 'STRENGTH', TRUE, FALSE, 60),
        -- Bíceps e antebraços
        ('Rosca direta', 'BARBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca direta', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca direta', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca direta', 'BAND', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca alternada', 'DUMBBELL', 'STRENGTH', TRUE, FALSE, 75),
        ('Rosca martelo', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca martelo', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca martelo', 'BAND', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca martelo cruzada', 'DUMBBELL', 'STRENGTH', TRUE, FALSE, 75),
        ('Rosca concentrada', 'DUMBBELL', 'STRENGTH', TRUE, FALSE, 75),
        ('Rosca Scott', 'BARBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca Scott', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca Scott', 'MACHINE', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca inclinada', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca spider', 'BARBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca spider', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca bayesiana', 'CABLE', 'STRENGTH', TRUE, FALSE, 75),
        ('Rosca inversa', 'BARBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca inversa', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca inversa', 'BAND', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca Zottman', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Rosca drag', 'BARBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Flexão de punho', 'BARBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Flexão de punho', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Flexão de punho', 'CABLE', 'STRENGTH', FALSE, FALSE, 60),
        ('Extensão de punho', 'BARBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Extensão de punho', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Extensão de punho', 'CABLE', 'STRENGTH', FALSE, FALSE, 60),
        ('Pronação do antebraço', 'DUMBBELL', 'STRENGTH', TRUE, FALSE, 60),
        ('Pronação do antebraço', 'CABLE', 'STRENGTH', TRUE, FALSE, 60),
        ('Pronação do antebraço', 'BAND', 'STRENGTH', TRUE, FALSE, 60),
        ('Supinação do antebraço', 'DUMBBELL', 'STRENGTH', TRUE, FALSE, 60),
        ('Supinação do antebraço', 'CABLE', 'STRENGTH', TRUE, FALSE, 60),
        ('Supinação do antebraço', 'BAND', 'STRENGTH', TRUE, FALSE, 60),
        ('Suspensão na barra', 'BODYWEIGHT', 'STRENGTH', FALSE, FALSE, 90),
        -- Tríceps
        ('Tríceps testa', 'BARBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Tríceps testa', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Tríceps testa', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Extensão de tríceps com corda', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Extensão de tríceps com barra reta', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Extensão de tríceps com barra V', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Tríceps francês', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Tríceps francês', 'BARBELL', 'STRENGTH', FALSE, FALSE, 75),
        ('Tríceps francês', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('Tríceps francês unilateral', 'DUMBBELL', 'STRENGTH', TRUE, FALSE, 75),
        ('Tríceps francês unilateral', 'CABLE', 'STRENGTH', TRUE, FALSE, 75),
        ('Tríceps coice', 'DUMBBELL', 'STRENGTH', TRUE, FALSE, 60),
        ('Tríceps coice', 'CABLE', 'STRENGTH', TRUE, FALSE, 60),
        ('Supino fechado', 'BARBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Mergulho no banco', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 90),
        ('Extensão de tríceps', 'MACHINE', 'STRENGTH', FALSE, FALSE, 75),
        ('Mergulho assistido', 'MACHINE', 'STRENGTH', FALSE, TRUE, 120),
        ('Extensão de tríceps acima da cabeça com corda', 'CABLE', 'STRENGTH', FALSE, FALSE, 75),
        ('JM press', 'BARBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Mergulho sentado', 'MACHINE', 'STRENGTH', FALSE, TRUE, 90),
        -- Quadríceps e glúteos
        ('Agachamento', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 120),
        ('Agachamento', 'BARBELL', 'STRENGTH', FALSE, TRUE, 150),
        ('Agachamento', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Agachamento', 'KETTLEBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Agachamento', 'MACHINE', 'STRENGTH', FALSE, TRUE, 150),
        ('Agachamento frontal', 'BARBELL', 'STRENGTH', FALSE, TRUE, 150),
        ('Agachamento goblet', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Agachamento goblet', 'KETTLEBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Agachamento sumô', 'BARBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Agachamento sumô', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Agachamento sumô', 'KETTLEBELL', 'STRENGTH', FALSE, TRUE, 120),
        ('Agachamento búlgaro', 'BODYWEIGHT', 'STRENGTH', TRUE, TRUE, 120),
        ('Agachamento búlgaro', 'BARBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Agachamento búlgaro', 'DUMBBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Afundo', 'BODYWEIGHT', 'STRENGTH', TRUE, TRUE, 120),
        ('Afundo', 'BARBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Afundo', 'DUMBBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Afundo reverso', 'BODYWEIGHT', 'STRENGTH', TRUE, TRUE, 120),
        ('Afundo reverso', 'DUMBBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Afundo reverso', 'KETTLEBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Afundo lateral', 'BODYWEIGHT', 'STRENGTH', TRUE, TRUE, 120),
        ('Afundo lateral', 'DUMBBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Afundo lateral', 'KETTLEBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Step-up', 'BODYWEIGHT', 'STRENGTH', TRUE, TRUE, 120),
        ('Step-up', 'BARBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Step-up', 'DUMBBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Leg press 45°', 'MACHINE', 'STRENGTH', FALSE, TRUE, 150),
        ('Leg press horizontal', 'MACHINE', 'STRENGTH', FALSE, TRUE, 150),
        ('Agachamento hack', 'MACHINE', 'STRENGTH', FALSE, TRUE, 150),
        ('Extensão de joelhos', 'MACHINE', 'STRENGTH', FALSE, FALSE, 75),
        ('Extensão unilateral de joelho', 'MACHINE', 'STRENGTH', TRUE, FALSE, 75),
        ('Agachamento sissy', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 90),
        ('Agachamento sissy', 'MACHINE', 'STRENGTH', FALSE, TRUE, 90),
        ('Agachamento isométrico na parede', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 75),
        ('Agachamento pistol', 'BODYWEIGHT', 'STRENGTH', TRUE, TRUE, 120),
        ('Agachamento espanhol', 'BAND', 'STRENGTH', FALSE, TRUE, 90),
        ('Agachamento dividido', 'BODYWEIGHT', 'STRENGTH', TRUE, TRUE, 120),
        ('Agachamento dividido', 'BARBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Agachamento dividido', 'DUMBBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Nordic reverso', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 90),
        -- Posteriores, glúteos e quadril
        ('Stiff', 'BARBELL', 'STRENGTH', FALSE, TRUE, 150),
        ('Stiff', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 150),
        ('Stiff', 'KETTLEBELL', 'STRENGTH', FALSE, TRUE, 150),
        ('Stiff unilateral', 'DUMBBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Stiff unilateral', 'KETTLEBELL', 'STRENGTH', TRUE, TRUE, 120),
        ('Flexão de joelhos deitado', 'MACHINE', 'STRENGTH', FALSE, FALSE, 75),
        ('Flexão de joelhos sentado', 'MACHINE', 'STRENGTH', FALSE, FALSE, 75),
        ('Flexão unilateral de joelho em pé', 'MACHINE', 'STRENGTH', TRUE, FALSE, 75),
        ('Flexão nórdica', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 120),
        ('Elevação pélvica', 'BARBELL', 'STRENGTH', FALSE, TRUE, 150),
        ('Elevação pélvica', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 150),
        ('Elevação pélvica', 'MACHINE', 'STRENGTH', FALSE, TRUE, 150),
        ('Ponte de glúteos', 'BODYWEIGHT', 'STRENGTH', FALSE, TRUE, 90),
        ('Ponte de glúteos', 'BARBELL', 'STRENGTH', FALSE, TRUE, 90),
        ('Ponte de glúteos', 'DUMBBELL', 'STRENGTH', FALSE, TRUE, 90),
        ('Ponte de glúteos', 'BAND', 'STRENGTH', FALSE, TRUE, 90),
        ('Pull-through', 'CABLE', 'STRENGTH', FALSE, TRUE, 90),
        ('Extensão de quadril', 'CABLE', 'STRENGTH', TRUE, FALSE, 75),
        ('Extensão de quadril', 'MACHINE', 'STRENGTH', TRUE, FALSE, 75),
        ('Extensão de quadril', 'BAND', 'STRENGTH', TRUE, FALSE, 75),
        ('Abdução de quadril', 'MACHINE', 'STRENGTH', FALSE, FALSE, 60),
        ('Abdução de quadril', 'CABLE', 'STRENGTH', TRUE, FALSE, 60),
        ('Abdução de quadril', 'BAND', 'STRENGTH', TRUE, FALSE, 60),
        ('Abdução de quadril', 'BODYWEIGHT', 'STRENGTH', TRUE, FALSE, 60),
        ('Adução de quadril', 'MACHINE', 'STRENGTH', FALSE, FALSE, 60),
        ('Adução de quadril', 'CABLE', 'STRENGTH', TRUE, FALSE, 60),
        ('Adução de quadril', 'BAND', 'STRENGTH', TRUE, FALSE, 60),
        ('Frog pump', 'BODYWEIGHT', 'STRENGTH', FALSE, FALSE, 60),
        ('Frog pump', 'BAND', 'STRENGTH', FALSE, FALSE, 60),
        ('Coice de glúteo', 'BODYWEIGHT', 'STRENGTH', TRUE, FALSE, 60),
        ('Coice de glúteo', 'BAND', 'STRENGTH', TRUE, FALSE, 60),
        ('Abdução de quadril em quatro apoios', 'BODYWEIGHT', 'STRENGTH', TRUE, FALSE, 60),
        ('Abdução de quadril em quatro apoios', 'BAND', 'STRENGTH', TRUE, FALSE, 60),
        ('Hiperextensão reversa', 'MACHINE', 'STRENGTH', FALSE, TRUE, 90),
        -- Panturrilhas e canelas
        ('Elevação de panturrilhas em pé', 'BODYWEIGHT', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação de panturrilhas em pé', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação de panturrilhas em pé', 'BARBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação de panturrilhas em pé', 'MACHINE', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação de panturrilhas sentado', 'DUMBBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação de panturrilhas sentado', 'BARBELL', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação de panturrilhas sentado', 'MACHINE', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação de panturrilhas no leg press', 'MACHINE', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação de panturrilhas unilateral', 'BODYWEIGHT', 'STRENGTH', TRUE, FALSE, 60),
        ('Elevação de panturrilhas unilateral', 'DUMBBELL', 'STRENGTH', TRUE, FALSE, 60),
        ('Elevação dos dedos dos pés', 'BODYWEIGHT', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação dos dedos dos pés', 'MACHINE', 'STRENGTH', FALSE, FALSE, 60),
        ('Elevação dos dedos dos pés', 'BAND', 'STRENGTH', FALSE, FALSE, 60),
        ('Eversão do tornozelo', 'BAND', 'STRENGTH', TRUE, FALSE, 45),
        ('Eversão do tornozelo', 'CABLE', 'STRENGTH', TRUE, FALSE, 45),
        -- Core
        ('Prancha', 'BODYWEIGHT', 'CORE', FALSE, TRUE, 45),
        ('Prancha lateral', 'BODYWEIGHT', 'CORE', TRUE, TRUE, 45),
        ('Prancha reversa', 'BODYWEIGHT', 'CORE', FALSE, TRUE, 45),
        ('Prancha com toque no ombro', 'BODYWEIGHT', 'CORE', TRUE, TRUE, 45),
        ('Dead bug', 'BODYWEIGHT', 'CORE', FALSE, TRUE, 45),
        ('Dead bug', 'BAND', 'CORE', FALSE, TRUE, 45),
        ('Bird dog', 'BODYWEIGHT', 'CORE', TRUE, TRUE, 45),
        ('Bird dog', 'BAND', 'CORE', TRUE, TRUE, 45),
        ('Crunch abdominal', 'BODYWEIGHT', 'CORE', FALSE, FALSE, 45),
        ('Crunch abdominal', 'CABLE', 'CORE', FALSE, FALSE, 60),
        ('Crunch abdominal', 'MACHINE', 'CORE', FALSE, FALSE, 60),
        ('Sit-up', 'BODYWEIGHT', 'CORE', FALSE, TRUE, 45),
        ('Abdominal reverso', 'BODYWEIGHT', 'CORE', FALSE, FALSE, 45),
        ('Elevação de joelhos suspenso', 'BODYWEIGHT', 'CORE', FALSE, TRUE, 60),
        ('Elevação de pernas suspenso', 'BODYWEIGHT', 'CORE', FALSE, TRUE, 60),
        ('Elevação de joelhos nas paralelas', 'BODYWEIGHT', 'CORE', FALSE, TRUE, 60),
        ('Rotação russa', 'BODYWEIGHT', 'CORE', FALSE, TRUE, 45),
        ('Rotação russa', 'DUMBBELL', 'CORE', FALSE, TRUE, 45),
        ('Rotação russa', 'KETTLEBELL', 'CORE', FALSE, TRUE, 45),
        ('Abdominal bicicleta', 'BODYWEIGHT', 'CORE', FALSE, TRUE, 45),
        ('Pallof press', 'CABLE', 'CORE', TRUE, TRUE, 60),
        ('Pallof press', 'BAND', 'CORE', TRUE, TRUE, 60),
        ('Rotação diagonal de tronco', 'CABLE', 'CORE', TRUE, TRUE, 60),
        ('Rotação diagonal de tronco', 'BAND', 'CORE', TRUE, TRUE, 60),
        ('Hollow body hold', 'BODYWEIGHT', 'CORE', FALSE, TRUE, 45),
        ('Abdominal em V', 'BODYWEIGHT', 'CORE', FALSE, TRUE, 45),
        ('Toque nos pés', 'BODYWEIGHT', 'CORE', FALSE, FALSE, 45),
        ('Toque nos calcanhares', 'BODYWEIGHT', 'CORE', FALSE, FALSE, 45),
        ('Dragon flag', 'BODYWEIGHT', 'CORE', FALSE, TRUE, 90),
        ('Caminhada unilateral com carga', 'DUMBBELL', 'CORE', TRUE, TRUE, 90),
        ('Caminhada unilateral com carga', 'KETTLEBELL', 'CORE', TRUE, TRUE, 90),
        -- Cardio
        ('Caminhada', 'BODYWEIGHT', 'CARDIO', FALSE, TRUE, NULL),
        ('Caminhada inclinada', 'MACHINE', 'CARDIO', FALSE, TRUE, NULL),
        ('Corrida', 'BODYWEIGHT', 'CARDIO', FALSE, TRUE, NULL),
        ('Corrida na esteira', 'MACHINE', 'CARDIO', FALSE, TRUE, NULL),
        ('Bicicleta ergométrica', 'MACHINE', 'CARDIO', FALSE, TRUE, NULL),
        ('Elíptico', 'MACHINE', 'CARDIO', FALSE, TRUE, NULL),
        ('Remo ergométrico', 'MACHINE', 'CARDIO', FALSE, TRUE, NULL),
        ('Escada ergométrica', 'MACHINE', 'CARDIO', FALSE, TRUE, NULL),
        ('Air bike', 'MACHINE', 'CARDIO', FALSE, TRUE, NULL),
        ('Ski ergômetro', 'MACHINE', 'CARDIO', FALSE, TRUE, NULL),
        ('Polichinelo', 'BODYWEIGHT', 'CARDIO', FALSE, TRUE, 30),
        ('Corrida estacionária', 'BODYWEIGHT', 'CARDIO', FALSE, TRUE, 30),
        ('Marcha estacionária', 'BODYWEIGHT', 'CARDIO', FALSE, TRUE, NULL),
        ('Subida de escadas', 'BODYWEIGHT', 'CARDIO', FALSE, TRUE, NULL),
        ('Boxe sombra', 'BODYWEIGHT', 'CARDIO', FALSE, TRUE, 30),
        -- Mobilidade
        ('Gato-vaca', 'BODYWEIGHT', 'MOBILITY', FALSE, TRUE, NULL),
        ('Postura da criança', 'BODYWEIGHT', 'MOBILITY', FALSE, TRUE, NULL),
        ('Alongamento mundial', 'BODYWEIGHT', 'MOBILITY', TRUE, TRUE, NULL),
        ('Transição de quadril 90/90', 'BODYWEIGHT', 'MOBILITY', TRUE, TRUE, NULL),
        ('Mobilização dos flexores do quadril', 'BODYWEIGHT', 'MOBILITY', TRUE, TRUE, NULL),
        ('Mobilização dos posteriores de coxa', 'BODYWEIGHT', 'MOBILITY', TRUE, FALSE, NULL),
        ('Mobilização de adutores em quatro apoios', 'BODYWEIGHT', 'MOBILITY', TRUE, TRUE, NULL),
        ('Mobilização de dorsiflexão do tornozelo', 'BODYWEIGHT', 'MOBILITY', TRUE, FALSE, NULL),
        ('Rotação torácica em quatro apoios', 'BODYWEIGHT', 'MOBILITY', TRUE, TRUE, NULL),
        ('Rotação torácica deitado', 'BODYWEIGHT', 'MOBILITY', TRUE, TRUE, NULL),
        ('Deslizamento de braços na parede', 'BODYWEIGHT', 'MOBILITY', FALSE, TRUE, NULL),
        ('Agachamento profundo sustentado', 'BODYWEIGHT', 'MOBILITY', FALSE, TRUE, NULL),
        ('Cachorro olhando para baixo', 'BODYWEIGHT', 'MOBILITY', FALSE, TRUE, NULL),
        ('Postura da cobra', 'BODYWEIGHT', 'MOBILITY', FALSE, TRUE, NULL),
        ('Postura do pombo', 'BODYWEIGHT', 'MOBILITY', TRUE, TRUE, NULL),
        ('Alongamento de panturrilha', 'BODYWEIGHT', 'MOBILITY', TRUE, FALSE, NULL),
        ('Mobilidade de punhos', 'BODYWEIGHT', 'MOBILITY', FALSE, FALSE, NULL),
        ('Rotação controlada de ombro', 'BODYWEIGHT', 'MOBILITY', TRUE, TRUE, NULL),
        ('Rotação controlada de quadril', 'BODYWEIGHT', 'MOBILITY', TRUE, TRUE, NULL),
        ('Agachamento cossaco', 'BODYWEIGHT', 'MOBILITY', TRUE, TRUE, NULL),
        ('Afundo com rotação torácica', 'BODYWEIGHT', 'MOBILITY', TRUE, TRUE, NULL),
        ('Passagem de ombros', 'BAND', 'MOBILITY', FALSE, TRUE, NULL),
        ('Alongamento de peitoral na parede', 'BODYWEIGHT', 'MOBILITY', TRUE, FALSE, NULL),
        ('Alongamento de dorsais', 'BODYWEIGHT', 'MOBILITY', FALSE, FALSE, NULL),
        -- Recuperação
        ('Caminhada leve', 'BODYWEIGHT', 'RECOVERY', FALSE, TRUE, NULL),
        ('Pedalada leve', 'MACHINE', 'RECOVERY', FALSE, TRUE, NULL),
        -- Condicionamento
        ('Burpee', 'BODYWEIGHT', 'CONDITIONING', FALSE, TRUE, 60),
        ('Agachamento com salto', 'BODYWEIGHT', 'CONDITIONING', FALSE, TRUE, 60),
        ('Afundo com salto', 'BODYWEIGHT', 'CONDITIONING', TRUE, TRUE, 60),
        ('Salto horizontal', 'BODYWEIGHT', 'CONDITIONING', FALSE, TRUE, 60),
        ('Escalador', 'BODYWEIGHT', 'CONDITIONING', TRUE, TRUE, 45),
        ('Bear crawl', 'BODYWEIGHT', 'CONDITIONING', TRUE, TRUE, 45),
        ('Crab walk', 'BODYWEIGHT', 'CONDITIONING', TRUE, TRUE, 45),
        ('Inchworm', 'BODYWEIGHT', 'CONDITIONING', FALSE, TRUE, 45),
        ('Salto patinador', 'BODYWEIGHT', 'CONDITIONING', TRUE, TRUE, 45),
        ('Corrida shuttle', 'BODYWEIGHT', 'CONDITIONING', FALSE, TRUE, 60),
        ('Deslocamento lateral', 'BODYWEIGHT', 'CONDITIONING', TRUE, TRUE, 45),
        ('Swing', 'KETTLEBELL', 'CONDITIONING', FALSE, TRUE, 90),
        ('Clean', 'KETTLEBELL', 'CONDITIONING', TRUE, TRUE, 90),
        ('Snatch', 'KETTLEBELL', 'CONDITIONING', TRUE, TRUE, 90),
        ('Clean and press', 'KETTLEBELL', 'CONDITIONING', TRUE, TRUE, 90),
        ('High pull', 'KETTLEBELL', 'CONDITIONING', TRUE, TRUE, 90),
        ('Turkish get-up', 'KETTLEBELL', 'CONDITIONING', TRUE, TRUE, 120),
        ('Thruster', 'DUMBBELL', 'CONDITIONING', FALSE, TRUE, 90),
        ('Thruster', 'BARBELL', 'CONDITIONING', FALSE, TRUE, 120),
        ('Thruster', 'KETTLEBELL', 'CONDITIONING', FALSE, TRUE, 90),
        ('Push press', 'DUMBBELL', 'CONDITIONING', FALSE, TRUE, 90),
        ('Push press', 'BARBELL', 'CONDITIONING', FALSE, TRUE, 120),
        ('Push press', 'KETTLEBELL', 'CONDITIONING', FALSE, TRUE, 90),
        ('Clean and press', 'BARBELL', 'CONDITIONING', FALSE, TRUE, 120),
        ('Clean and press', 'DUMBBELL', 'CONDITIONING', FALSE, TRUE, 90),
        ('Caminhada do fazendeiro', 'DUMBBELL', 'CONDITIONING', FALSE, TRUE, 90),
        ('Caminhada do fazendeiro', 'KETTLEBELL', 'CONDITIONING', FALSE, TRUE, 90),
        ('Sprint no remo ergométrico', 'MACHINE', 'CONDITIONING', FALSE, TRUE, 60),
        ('Sprint na bicicleta', 'MACHINE', 'CONDITIONING', FALSE, TRUE, 60),
        ('Sprint na esteira', 'MACHINE', 'CONDITIONING', FALSE, TRUE, 60)
)
INSERT INTO exercises (
    name,
    equipment_type_id,
    activity_type_id,
    unilateral,
    compound,
    suggested_rest_seconds,
    active,
    created_at
)
SELECT
    seed.name,
    (SELECT id FROM equipment_types WHERE code = seed.equipment_code),
    (SELECT id FROM activity_types WHERE code = seed.activity_code),
    seed.unilateral,
    seed.compound,
    seed.suggested_rest_seconds,
    TRUE,
    CURRENT_TIMESTAMP
FROM exercise_seed seed;
